language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
install:
- pip install .
script: py.test
env:
- PUSHBULLET_API_KEY=RrFnc1xaeQXnRrr2auoGA1e8pQ8MWmMF
deploy:
  provider: pypi
  user: randomchars
  password:
    secure: L8FjGe1aEDv7QJyv54HLhDoD3a5dze8xziGwW/Pjj1QBkyBPw9gwN65/T7VugU+GV1pPLcC8ESN0O+LdEQ9BHnQ7Jgm/xjKC6Ncmq+1I+RGdQRyM/Fqv5fHeTGhi5iimYeKzf07gBC7NzAy1smDMJm9MNY6RRqaInChdanjHvcQ=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
